pipeline {
    agent any
     tools {
        gradle '7.5.1'
        }

    stages {
        stage('Clone Repository') {
               steps {
                      git branch: 'develop', credentialsId: '112f9878-7c13-4fe6-a745-f95f0c4f47ed', url: 'https://github.com/alberto8598/pry2.git'
                      }
             }
               stage('JAVA Version') {
                     steps {
                           withGradle {
                                    sh 'java --version'
                                 }
                           }
                   }
        stage('Ejecutar pruebas unitarias') {
            steps {
                  withGradle {
                         sh 'gradle test'
                             }
            }
        }

        stage('build Gradle Project') {
                steps {
                      withGradle {
                               sh 'gradle clean build'
                            }
                      }
              }

       stage('Quality Scan Project') {
           environment {
               scannerHome = tool 'SonarQubeScanner'
           }
           steps {
               withSonarQubeEnv('SonarQubeServer') {
                   sh "gradle sonarqube -Dsonar.login=admin -Dsonar.password=Pesunita1_ -Dsonar.projectKey=pry2"
               }
           }
       }
        stage('Construir imagen Docker') {
            steps {
                sh 'docker build -t myapp .'
            }
        }
        stage('Subir imagen Docker') {
           steps {
              withDockerRegistry([credentialsId: '7dd3df4f-f53c-4ad2-bf16-d5352962ae9c', url: 'https://index.docker.io/v1/']) {
                           sh 'docker push curribifine/credibanco'
                 }
            }
        }
    }
}