pipeline {
    agent any

    stages {
        stage('Clone Repository') {
               steps {
                      git branch: 'develop', credentialsId: '112f9878-7c13-4fe6-a745-f95f0c4f47ed', url: 'https://github.com/alberto8598/pry2.git'
                      }
             }
        stage('Ejecutar pruebas unitarias') {
            steps {
                  withGradle {
                         sh 'gradle Test'
                             }
            }
        }
		stage('Quality Scan Project') {
           environment {
               scannerHome = tool 'SonarQubeScanner'
           }
           steps {
               withSonarQubeEnv('SonarQubeServer') {
                   sh "gradle sonarqube -Dsonar.login=admin -Dsonar.password=Pesunita1_ -Dsonar.projectKey=pry2"
               }
           }
       }
    stage('Build Image Docker') {
        steps {
            script {

                dockerImage = docker.build('curribifine/credibanco', '-f deployment/Dockerfile .')
            }
        }
    }
        stage('Subir imagen Docker') {
           steps {
              withDockerRegistry([credentialsId: '7dd3df4f-f53c-4ad2-bf16-d5352962ae9c', url: 'https://index.docker.io/v1/']) {
                           sh 'docker push curribifine/credibanco'
                 }
            }
        }
    }
}